### ISSUE TITLE
Can't authenticate without Vault 

### ISSUE THREAD

**Issue by pkcharoen** [jeremmfr/terraform-provider-iptables#1]
Hi,

We are seeing problem planning/applying iptables rules with Terraform when iptables-api requires basic http authentication. Seems like "login" and "password" on provider don't work with "vault_enable" option. We are passing username/password for basic https authentication and not storing in Vault.

Disabling authentication on iptables-api and commenting out login/password on terraform provider, terraform plan/apply work as expected.

Terraform file
```
terraform {
  required_providers {
    iptables = {
      source  = "local/providers/iptables"
      version = "1.1.1"
    }
  }
}
provider "iptables" {
  firewall_ip         = "10.177.57.106"
  port                = 8888
  allowed_cidr_blocks = ["0.0.0.0/0"]
  https               = true
  insecure            = true
  ipv6_enable         = false
  vault_enable        = false
  login               = "iptables"
  password            = "notpassword"
}
....
```

```
$terraform plan
╷
│ Error: "vault_enable": conflicts with login
│
│   with provider["local/providers/iptables"],
│   on main.tf line 10, in provider "iptables":
│   10: provider "iptables" {
│
╵
```

Here's the command and parameters for iptables-api
```
iptables-api -https -ip=0.0.0.0 -port=8888 -log=/var/log/iptables-api.access.log -cert=/root/iptables-api/cert.pem -key=/root/iptables-api/key.pem -htpasswd=/root/.htpasswd
```

**Comment by soupdiver** [comment]
It seems defining a default for `vault_enable` does not work (well) together with the usage of `ConflictsWith`. See: https://github.com/jeremmfr/terraform-provider-iptables/blob/master/iptables/provider.go#L69-L70

In my testing the result is that `vault_enable` is always set and once you specify `login` and/or `password` you get the mentioned error.
Not setting a default for `vault_enable` seems to fix the issue for me

**Comment by jeremmfr** [comment]
Ok, I take care to fix that
